
# This manifest runs the contiv-cleanup container
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: contiv-cleanup
  namespace: kube-system
  labels:
    k8s-app: contiv-cleanup
spec:
  selector:
    matchLabels:
      k8s-app: contiv-cleanup
  template:
    metadata:
      labels:
        k8s-app: contiv-cleanup
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        # Runs netplugin cleanup container on each Kubernetes node.
        - name: contiv-cleanup
          image: contiv/netplugin:__CONTIV_VERSION__
          args:
            - -pkubernetes
            - -r
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/openvswitch
              name: etc-openvswitch
              readOnly: false
            - mountPath: /var/run
              name: var-run
              readOnly: false
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
            - mountPath: /opt/cni/bin
              name: cni-bin-dir
              readOnly: false
            - mountPath: /etc/cni/net.d/
              name: etc-cni-dir
              readOnly: false
      volumes:
        # Used by contiv-cleanup
        - name: etc-openvswitch
          hostPath:
            path: /etc/openvswitch
        - name: var-run
          hostPath:
            path: /var/run
        - name: var-contiv
          hostPath:
            path: /var/contiv
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: etc-cni-dir
          hostPath:
            path: /etc/cni/net.d/
---

